/* Pamet v1.0.3 — product/brand/billing/sharing layer */
(function(){
  "use strict";
  const S=window.PametStore,A=window.PametAuth,$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  if(!S||!A)return;
  const PLANS={
    free:{name:"Free",position:"Track",price:"$0",summary:"Build your health history.",features:["Unlimited daily logging","90-day history","Weekly summary","3 custom trackers","1 reminder","1 Visit Brief/month"]},
    pro:{name:"Pro",position:"Understand",price:"$6.99/mo · $59.99/yr",summary:"Find patterns and trends in your health history.",features:["Unlimited history","Correlation insights","Advanced trends","What Changed?","Unlimited trackers","Unlimited reminders","Unlimited Visit Briefs","Basic sharing"]},
    ultra:{name:"Ultra",position:"Prepare",price:"$12.99/mo · $99.99/yr",summary:"Turn your health history into better conversations with your care team.",features:["Everything in Pro","Multi-profile management","Multiple caregivers","Role-based permissions","Appointment preparation","Longitudinal analysis","Advanced Visit Briefs","Priority support"]}
  };
  let cfg=null;
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  function toast(m,bad=false){let e=$('.pamet-toast');if(e)e.remove();e=document.createElement('div');e.className='pamet-toast'+(bad?' error':'');e.textContent=m;document.body.appendChild(e);setTimeout(()=>e.remove(),3500)}
  function cred(){return A.getBackendCredential?A.getBackendCredential():null}
  async function api(path,opt={}){const c=cred(),h={"Content-Type":"application/json",...(opt.headers||{})};if(c?.deviceKey)h.Authorization=`Bearer ${c.deviceKey}`;const r=await fetch(path,{...opt,headers:h});const t=await r.text();let b={};try{b=t?JSON.parse(t):{}}catch{b={error:t}}if(!r.ok)throw new Error(b.error||`Request failed (${r.status})`);return b}
  async function bootstrap(silent=true){const c=cred();if(!c)return null;try{const b=await api('/api/account/bootstrap',{method:'POST',body:JSON.stringify({...c,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC'})});if(b.user?.plan&&PLANS[b.user.plan]){S._settings.plan=b.user.plan;S.persistSettings()}return b}catch(e){if(!silent)toast('Secure Pamet services are not configured on this deployment yet.',true);return null}}
  function paid(){return ['pro','ultra'].includes(S.settings.plan)}
  function ultra(){return S.settings.plan==='ultra'}
  S.isPro=paid;S.isUltra=ultra;
  if(S.PLANS){Object.keys(S.PLANS).forEach(k=>delete S.PLANS[k]);Object.assign(S.PLANS,PLANS)}
  S.plan=()=>PLANS[S.settings.plan]||PLANS.free;
  S.patternLimit=()=>paid()?Infinity:1;
  S.customLimit=()=>paid()?Infinity:3;
  S.addCustomField=function(category,name){const key={symptoms:'customSymptoms',moods:'customMoods',activities:'customActivities',meds:'customMeds'}[category],canon={symptoms:S.SYMPTOMS,moods:S.MOODS,activities:S.ACTIVITIES,meds:S.MEDS}[category];if(!key||!name)return false;const clean=String(name).trim(),list=S._settings[key]||[];if(!clean||list.includes(clean)||(canon||[]).includes(clean))return false;if(!paid()){const total=['customSymptoms','customMoods','customActivities','customMeds'].reduce((n,k)=>n+(S._settings[k]||[]).length,0);if(total>=3)return false}list.push(clean);S._settings[key]=list;S.persistSettings();return true};
  const oldPatterns=S.patterns.bind(S);S.patterns=()=>oldPatterns().map(p=>({...p,title:String(p.title||'').replace(/\s*→\s*/g,' and ').replace(/^Emerging:\s*/,'Emerging pattern: '),detail:String(p.detail||'').replace(/you develop a headache within 12 hours/gi,'headache was reported within the following 12 hours').replace(/Hydrating more may ease the midday dip\.?/gi,'This is an observation from your logged data, not a treatment recommendation.').replace(/Consider warm-up and cool-down routines\.?/gi,'This observation does not establish that activity caused the symptom.').replace(/correlation/gi,'observed relationship')}));
  function brand(){document.title='Pamet — Your health history, finally useful';const theme=$('meta[name="theme-color"]');if(theme)theme.content='#0F3D3E';$$('.brand-mark').forEach(m=>{if(!m.querySelector('img')){m.textContent='';const i=document.createElement('img');i.src='assets/pamet-mark.svg';i.alt='';m.appendChild(i)}});const tag=$('.welcome-tagline');if(tag)tag.textContent='Your health history, finally useful.';const sw=$('#loginForm .welcome-switch');if(sw)sw.hidden=A.hasAccount();const pt=$('#screen-patterns .screen-title');if(pt)pt.textContent='Insights';const rt=$('#screen-report .screen-title');if(rt)rt.textContent='Visit Brief';const f=$('.footer-line');if(f)f.textContent='Pamet v1.0.3 · Your health history, finally useful.';const u=$('.streak-unit');if(u)u.textContent='days logged';const sub=$('.streak-sub');if(sub)sub.textContent='Each entry adds context to your health history.';const k=$('#insightBanner .insight-kicker');if(k)k.textContent='OBSERVATION — BASED ON YOUR LOGS'}
  function modal(html){let r=$('#pametModalRoot');if(!r){r=document.createElement('div');r.id='pametModalRoot';document.body.appendChild(r)}r.innerHTML=`<div class="pamet-modal-backdrop"><section class="pamet-modal" role="dialog" aria-modal="true">${html}</section></div>`;r.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>r.innerHTML='');r.querySelector('.pamet-modal-backdrop').onclick=e=>{if(e.target===e.currentTarget)r.innerHTML=''};return r}
  async function billingConfig(){if(cfg)return cfg;cfg=await api('/api/billing/config');return cfg}
  async function checkout(plan='pro',interval='annual'){try{await bootstrap(false);const c=await billingConfig();if(!c.publishableKey)throw new Error('Stripe is not configured yet.');if(plan==='ultra'&&!c.ultraEnabled)throw new Error('Ultra is planned for Phase 2 and is not available for purchase yet.');if(!window.Stripe){await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://js.stripe.com/v3/';s.onload=ok;s.onerror=no;document.head.appendChild(s)})}const out=await api('/api/billing/create-subscription',{method:'POST',body:JSON.stringify({plan,interval})});const r=modal(`<div class="pamet-modal-head"><div><h2 class="pamet-modal-title">Activate Pamet ${PLANS[plan].name}</h2><p class="pamet-modal-sub">Card fields are securely provided by Stripe.</p></div><button class="pamet-close" data-close>×</button></div><form id="payForm"><div id="paymentElement" class="pamet-payment-box"></div><div id="payError" class="pamet-payment-error"></div><button class="btn btn-primary btn-block" style="margin-top:14px">Confirm ${PLANS[plan].name}</button></form>`);const stripe=Stripe(c.publishableKey),elements=stripe.elements({clientSecret:out.clientSecret,appearance:{theme:'stripe',variables:{colorPrimary:'#4CAF7A',colorText:'#263638',colorDanger:'#8E3B4F',borderRadius:'10px'}}}),pe=elements.create('payment');pe.mount('#paymentElement');r.querySelector('#payForm').onsubmit=async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button'),err=r.querySelector('#payError');btn.disabled=true;btn.textContent='Confirming…';const params={return_url:`${location.origin}${location.pathname}?billing=complete`};const result=out.intentType==='setup'?await stripe.confirmSetup({elements,confirmParams:params,redirect:'if_required'}):await stripe.confirmPayment({elements,confirmParams:params,redirect:'if_required'});if(result.error){err.textContent=result.error.message;btn.disabled=false;btn.textContent=`Confirm ${PLANS[plan].name}`;return}const sync=await api('/api/billing/sync',{method:'POST',body:'{}'});if(sync.user?.plan){S._settings.plan=sync.user.plan;S.persistSettings()}r.innerHTML='';settings();toast(`Pamet ${PLANS[plan].name} is active.`)}}catch(e){toast(e.message,true)}}
  async function portal(){try{await bootstrap(false);const o=await api('/api/billing/portal',{method:'POST',body:'{}'});if(o.url)location.href=o.url}catch(e){toast(e.message,true)}}
  function planModal(){const r=modal(`<div class="pamet-modal-head"><div><h2 class="pamet-modal-title">See what's changing in your health</h2><p class="pamet-modal-sub">Track for free. Upgrade when you want deeper understanding or appointment preparation.</p></div><button class="pamet-close" data-close>×</button></div><div class="pamet-plan-grid">${['free','pro','ultra'].map(k=>`<button class="pamet-plan-option" data-plan="${k}" ${k==='free'?'disabled':''}><strong>${PLANS[k].name} · ${PLANS[k].position}</strong><small>${PLANS[k].summary}</small><div class="price">${PLANS[k].price}</div></button>`).join('')}</div><div class="pamet-billing-toggle"><button class="active" data-int="annual">Annual · Save 28%</button><button data-int="monthly">Monthly</button></div><p class="pamet-reassurance">Paid plans support a 7-day trial when billing is configured. Annual is preferred. Cancel anytime. Pamet has no advertising on any plan.</p><button class="data-btn" data-close style="margin-top:8px">Not now</button>`);let interval='annual';r.querySelectorAll('[data-int]').forEach(b=>b.onclick=()=>{interval=b.dataset.int;r.querySelectorAll('[data-int]').forEach(x=>x.classList.toggle('active',x===b))});r.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>checkout(b.dataset.plan,interval))}
  function access(kind){if(!paid()){toast(`${kind==='caregiver'?'Caregiver access':'Primary Care Access'} requires Pro.`);return planModal()}const title=kind==='caregiver'?'Caregiver access':'Primary Care Access',r=modal(`<div class="pamet-modal-head"><div><h2 class="pamet-modal-title">${title}</h2><p class="pamet-modal-sub">Create a secure, read-only share. Access is revocable and does not provide monitoring, alerts, diagnosis, or a live doctor portal.</p></div><button class="pamet-close" data-close>×</button></div><form id="accessForm" class="pamet-form"><label>Name<input id="accessName" required maxlength="100"></label><label>Email<input id="accessEmail" type="email" required maxlength="254"></label>${kind==='provider'?'<label>Practice / organization (optional)<input id="accessOrg" maxlength="120"></label>':''}<label><span><input id="includeNotes" type="checkbox" style="width:auto;margin-right:6px"> Include recent notes</span></label><div class="pamet-form-actions"><button type="button" class="btn btn-ghost" data-close>Cancel</button><button class="btn btn-primary">Send secure invitation</button></div></form><div id="accessList" class="pamet-access-list"></div>`);const load=async()=>{try{await bootstrap(false);const o=await api(`/api/sharing/invites?kind=${kind}`);r.querySelector('#accessList').innerHTML=o.invites?.length?o.invites.map(i=>`<div class="pamet-access-item"><div><strong>${esc(i.name)}</strong><small>${esc(i.email)} · ${esc(i.status)}</small></div><button class="pamet-text-button" data-revoke="${esc(i.id)}">Revoke</button></div>`).join(''):'<small>No one currently has access.</small>';r.querySelectorAll('[data-revoke]').forEach(b=>b.onclick=async()=>{await api(`/api/sharing/invites/${encodeURIComponent(b.dataset.revoke)}`,{method:'DELETE'});toast('Access revoked.');load()})}catch(e){r.querySelector('#accessList').innerHTML=`<small>${esc(e.message)}</small>`}};r.querySelector('#accessForm').onsubmit=async e=>{e.preventDefault();try{await bootstrap(false);const rep=S.report();await api('/api/sharing/invites',{method:'POST',body:JSON.stringify({kind,name:r.querySelector('#accessName').value,email:r.querySelector('#accessEmail').value,organization:r.querySelector('#accessOrg')?.value||'',snapshot:{generatedAt:new Date().toISOString(),rangeLabel:rep.rangeLabel,overview:rep.overview,symptoms:rep.breakdown,patterns:(rep.patterns||[]).map(p=>({title:p.title,detail:p.detail,occurrences:p.occurrences})),medications:rep.medications,notes:r.querySelector('#includeNotes').checked?rep.notes:[],disclaimer:'Generated from information recorded by the user. This is not a medical diagnosis or clinical assessment.'}})});toast('Secure invitation sent.');e.currentTarget.reset();load()}catch(x){toast(x.message,true)}};load()}
  async function digest(e){e.stopImmediatePropagation();const on=e.target.checked;try{await bootstrap(false);const entries=S._entries.filter(x=>new Date(x.date)>new Date(Date.now()-7*86400000)),counts={};entries.forEach(x=>(x.symptoms||[]).forEach(s=>counts[s]=(counts[s]||0)+1));const snap={periodEnd:new Date().toISOString(),loggedDays:new Set(entries.map(x=>String(x.date).slice(0,10))).size,symptomDays:entries.filter(x=>(x.symptoms||[]).length).length,topSymptoms:Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([name,count])=>({name,count})),averageSeverity:entries.length?+(entries.reduce((n,x)=>n+(+x.severity||0),0)/entries.length).toFixed(1):0,averageSleep:entries.length?+(entries.reduce((n,x)=>n+(+x.sleepHours||0),0)/entries.length).toFixed(1):0,observations:[]};await api('/api/preferences/weekly-digest',{method:'POST',body:JSON.stringify({enabled:on,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC',snapshot:on?snap:null})});S.setSetting('weeklyDigest',on);localStorage.setItem('pamet_weekly_digest_consent_v102',on?'yes':'no');toast(on?'Weekly digest enabled for your Pamet email.':'Weekly digest turned off.')}catch(x){e.target.checked=!on;toast(x.message,true)}}
  function whatChanged(){const list=$('#patternList');if(!list)return;let box=$('#pametWhatChanged');if(!box){box=document.createElement('section');box.id='pametWhatChanged';box.className='pamet-whatchanged';list.parentNode.insertBefore(box,list)}if(!paid()){box.innerHTML='<h3>What Changed?</h3><p class="pamet-modal-sub">Compare the last 30 days with the previous 30 days.</p><button class="btn btn-ghost">Explore with Pro</button>';box.querySelector('button').onclick=planModal;return}const now=Date.now(),cur=S._entries.filter(e=>new Date(e.date)>=new Date(now-30*86400000)),prev=S._entries.filter(e=>new Date(e.date)>=new Date(now-60*86400000)&&new Date(e.date)<new Date(now-30*86400000)),all={};cur.concat(prev).forEach(e=>(e.symptoms||[]).forEach(s=>all[s]=(all[s]||0)+1));const top=Object.keys(all).sort((a,b)=>all[b]-all[a]).slice(0,4);box.innerHTML=`<h3>What Changed?</h3><p class="pamet-modal-sub">Last 30 days vs. previous 30 days. These are observations, not medical conclusions.</p><div class="pamet-change-grid">${(top.length?top:['Not enough data']).map(s=>{if(s==='Not enough data')return '<div class="pamet-change"><strong>Not enough data</strong><span>Keep logging to compare periods.</span></div>';const a=cur.filter(e=>(e.symptoms||[]).includes(s)).length,b=prev.filter(e=>(e.symptoms||[]).includes(s)).length,d=a-b;return `<div class="pamet-change"><strong>${esc(s)} · ${d===0?'→ Stable':d>0?'↑ '+d:'↓ '+Math.abs(d)}</strong><span>${a} vs ${b} logged days</span></div>`}).join('')}</div>`}
  function settings(){brand();const custom=$('#customSymptomList')?.closest('.settings-card');if(custom)custom.remove();['#setStreakReminders','#setE2e'].forEach(id=>$(id)?.closest('.setting-row')?.classList.add('pamet-removed-setting'));const cur=PLANS[S.settings.plan]?S.settings.plan:'free',pc=$('#planCompare'),pl=$('#planLineText');if(pl)pl.textContent=`${PLANS[cur].name} · ${PLANS[cur].position}`;if(pc)pc.innerHTML=`<div class="pamet-plan-shell"><div class="pamet-current-plan"><div><strong>${PLANS[cur].name} · ${PLANS[cur].position}</strong><div class="pamet-plan-positioning">${PLANS[cur].summary}</div></div><div class="pamet-plan-price">${PLANS[cur].price}</div></div><ul class="pamet-plan-summary">${PLANS[cur].features.slice(0,5).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`;const up=$('#upgradeBtn');if(up&&!up.dataset.v102){up.dataset.v102=1;up.disabled=false;up.textContent=cur==='free'?'See Pro & Ultra':'Manage your plan';up.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();cur==='free'?planModal():portal()},true)}[['#setCaregiver','caregiver'],['#setPrimaryCare','provider']].forEach(([id,k])=>{const t=$(id),row=t?.closest('.setting-row'),lab=row?.querySelector('.setting-label');if(!t||!row)return;t.disabled=!paid();if(!paid())t.checked=false;if(lab&&!lab.querySelector('.pamet-lock-badge')){const b=document.createElement('span');b.className='pamet-lock-badge';b.textContent='Pro+';lab.appendChild(b)}if(!row.dataset.v102){row.dataset.v102=1;row.addEventListener('click',e=>{if(e.target.closest('.help'))return;e.preventDefault();e.stopImmediatePropagation();access(k)},true)}});const wd=$('#setWeeklyDigest');if(wd){if(localStorage.getItem('pamet_weekly_digest_consent_v102')!=='yes'){S.setSetting('weeklyDigest',false);wd.checked=false}if(!wd.dataset.v102){wd.dataset.v102=1;wd.addEventListener('change',digest,true)}}}
  function reportDisclaimer(){const d=$('#reportDoc');if(d&&!d.querySelector('.pamet-report-disclaimer')){const p=document.createElement('p');p.className='pamet-report-disclaimer';p.style.cssText='margin:18px 0 0;padding-top:12px;border-top:1px solid var(--border-color);font-size:11px;color:var(--text-tertiary)';p.textContent='Generated from information recorded by the user. This is not a medical diagnosis or clinical assessment.';d.appendChild(p)}}
  async function sync(){try{const b=await bootstrap(true);if(!b)return;cfg=await api('/api/billing/config');const st=await api('/api/billing/status');if(st.user?.plan&&PLANS[st.user.plan]){S._settings.plan=st.user.plan;S.persistSettings()}}catch{}}
  brand();settings();whatChanged();reportDisclaimer();$$('.tab[data-tab]').forEach(t=>t.addEventListener('click',()=>setTimeout(()=>{settings();if(t.dataset.tab==='patterns')whatChanged();if(t.dataset.tab==='report')reportDisclaimer()},0)));window.addEventListener('pamet:profile-updated',()=>bootstrap(true));sync().then(settings);
})();
