'use strict';

const path=require('path');
const crypto=require('crypto');
const express=require('express');
const mysql=require('mysql2/promise');
const Stripe=require('stripe');
const app=express();
const PORT=Number(process.env.PORT||8080);
const APP=(process.env.APP_BASE_URL||`http://localhost:${PORT}`).replace(/\/$/,'');
const stripe=process.env.STRIPE_SECRET_KEY?new Stripe(process.env.STRIPE_SECRET_KEY):null;
const prices={pro:{monthly:process.env.STRIPE_PRICE_PRO_MONTHLY||'',annual:process.env.STRIPE_PRICE_PRO_ANNUAL||''},ultra:{monthly:process.env.STRIPE_PRICE_ULTRA_MONTHLY||'',annual:process.env.STRIPE_PRICE_ULTRA_ANNUAL||''}};
const ultraEnabled=String(process.env.ULTRA_ENABLED||'').toLowerCase()==='true';
let pool;
const sha=v=>crypto.createHash('sha256').update(String(v)).digest('hex');
const token=()=>crypto.randomBytes(32).toString('hex');
const clean=(v,n)=>String(v||'').trim().slice(0,n);
const emailOk=e=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e);
const parse=(v,d={})=>{if(v&&typeof v==='object')return v;try{return JSON.parse(v)}catch{return d}};
const html=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

async function db(){
  if(pool)return pool;
  if(!process.env.DATABASE_URL&&!process.env.DB_HOST)throw new Error('Database is not configured.');
  pool=mysql.createPool(process.env.DATABASE_URL||{host:process.env.DB_HOST,port:Number(process.env.DB_PORT||3306),database:process.env.DB_NAME,user:process.env.DB_USER,password:process.env.DB_PASSWORD,ssl:process.env.DB_SSL==='true'?{rejectUnauthorized:false}:undefined,waitForConnections:true,connectionLimit:5});
  await schema(); return pool;
}
async function schema(){
  await pool.query(`CREATE TABLE IF NOT EXISTS pamet_users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,local_user_id VARCHAR(128) NOT NULL UNIQUE,device_key_hash CHAR(64) NOT NULL UNIQUE,email VARCHAR(254) NOT NULL UNIQUE,first_name VARCHAR(100) NOT NULL DEFAULT '',last_name VARCHAR(100) NOT NULL DEFAULT '',timezone VARCHAR(100) NOT NULL DEFAULT 'UTC',plan VARCHAR(16) NOT NULL DEFAULT 'free',subscription_status VARCHAR(32) NOT NULL DEFAULT 'none',stripe_customer_id VARCHAR(128) NULL UNIQUE,stripe_subscription_id VARCHAR(128) NULL UNIQUE,weekly_digest_enabled BOOLEAN NOT NULL DEFAULT FALSE,latest_digest_json JSON NULL,confirmation_email_sent_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_digest(weekly_digest_enabled)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await pool.query(`CREATE TABLE IF NOT EXISTS pamet_sharing_invites (id CHAR(36) PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,kind VARCHAR(20) NOT NULL,name VARCHAR(100) NOT NULL,email VARCHAR(254) NOT NULL,organization VARCHAR(120) NOT NULL DEFAULT '',status VARCHAR(20) NOT NULL DEFAULT 'active',share_token_hash CHAR(64) NOT NULL UNIQUE,snapshot_json JSON NOT NULL,expires_at DATETIME NOT NULL,revoked_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES pamet_users(id) ON DELETE CASCADE,INDEX idx_share(user_id,kind,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await pool.query(`CREATE TABLE IF NOT EXISTS pamet_audit_log (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NULL,event_type VARCHAR(80) NOT NULL,event_json JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_audit(user_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await pool.query(`CREATE TABLE IF NOT EXISTS pamet_feedback (id CHAR(36) PRIMARY KEY,category VARCHAR(24) NOT NULL,rating TINYINT UNSIGNED NULL,message VARCHAR(1000) NOT NULL,app_version VARCHAR(16) NOT NULL,screen VARCHAR(40) NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_feedback_created(created_at),INDEX idx_feedback_category(category)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
}
async function audit(userId,type,data={}){try{const p=await db();await p.execute('INSERT INTO pamet_audit_log(user_id,event_type,event_json) VALUES(?,?,?)',[userId||null,type,JSON.stringify(data)])}catch{}}
async function mail(to,subject,body){
  if(!process.env.RESEND_API_KEY||!process.env.EMAIL_FROM)return false;
  const shell=`<!doctype html><html><body style="margin:0;background:#F4F5F2;font-family:Arial,sans-serif;color:#263638"><div style="max-width:600px;margin:auto;padding:32px 18px"><div style="background:#fff;border:1px solid #DDE3DF;border-radius:16px;padding:28px"><div style="font-size:24px;font-weight:700;color:#0F3D3E;margin-bottom:20px">Pamet</div>${body}</div><p style="font-size:12px;color:#5B6B73">Your health history, finally useful.</p></div></body></html>`;
  const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.EMAIL_FROM,to:[to],subject,html:shell})});
  if(!r.ok)throw new Error('Email delivery failed.'); return true;
}
function publicUser(u){return{id:String(u.id),email:u.email,firstName:u.first_name,lastName:u.last_name,plan:u.plan||'free',subscriptionStatus:u.subscription_status||'none',weeklyDigest:!!u.weekly_digest_enabled}}

// Stripe webhooks must be registered before express.json so the raw body is preserved.
app.post('/api/stripe/webhook',express.raw({type:'application/json'}),async(req,res)=>{
  if(!stripe||!process.env.STRIPE_WEBHOOK_SECRET)return res.status(503).json({error:'Stripe webhook not configured.'});
  try{const ev=stripe.webhooks.constructEvent(req.body,req.headers['stripe-signature'],process.env.STRIPE_WEBHOOK_SECRET);if(ev.type.startsWith('customer.subscription.'))await syncSubscription(ev.data.object);await audit(null,`stripe.${ev.type}`,{id:ev.id});res.json({received:true})}catch(e){res.status(400).json({error:e.message})}
});
app.use(express.json({limit:'256kb'}));
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');if(req.path.startsWith('/api/'))res.setHeader('Cache-Control','no-store');next()});

async function auth(req,res,next){
  try{const a=String(req.headers.authorization||''),k=a.startsWith('Bearer ')?a.slice(7).trim():'';if(k.length<40)return res.status(401).json({error:'Authentication required.'});const p=await db(),[rows]=await p.execute('SELECT * FROM pamet_users WHERE device_key_hash=? LIMIT 1',[sha(k)]);if(!rows.length)return res.status(401).json({error:'Authentication required.'});req.user=rows[0];next()}catch(e){next(e)}
}
app.get('/api/health',(req,res)=>res.json({ok:true,version:'1.0.3'}));
app.post('/api/account/bootstrap',async(req,res,next)=>{
  try{const local=clean(req.body.localUserId,128),key=clean(req.body.deviceKey,256),email=clean(req.body.email,254).toLowerCase(),first=clean(req.body.firstName,100),last=clean(req.body.lastName,100),tz=clean(req.body.timezone||'UTC',100);if(!local||key.length<40||!emailOk(email))return res.status(400).json({error:'A valid local Pamet account is required.'});const p=await db(),kh=sha(key),[rows]=await p.execute('SELECT * FROM pamet_users WHERE local_user_id=? OR email=?',[local,email]);let u=rows.find(x=>x.local_user_id===local),created=false;if(u){if(u.device_key_hash!==kh)return res.status(403).json({error:'This device credential does not match the account.'});await p.execute('UPDATE pamet_users SET email=?,first_name=?,last_name=?,timezone=? WHERE id=?',[email,first,last,tz,u.id])}else{if(rows.some(x=>x.email===email))return res.status(409).json({error:'This email is already linked to another Pamet installation.'});const [r]=await p.execute('INSERT INTO pamet_users(local_user_id,device_key_hash,email,first_name,last_name,timezone) VALUES(?,?,?,?,?,?)',[local,kh,email,first,last,tz]);const [fresh]=await p.execute('SELECT * FROM pamet_users WHERE id=?',[r.insertId]);u=fresh[0];created=true}const [fresh]=await p.execute('SELECT * FROM pamet_users WHERE id=?',[u.id]);u=fresh[0];let emailSent=false;if((created||!u.confirmation_email_sent_at)&&process.env.RESEND_API_KEY){try{emailSent=await mail(u.email,'Welcome to Pamet',`<h1 style="font-size:22px">Thanks for registering with Pamet.</h1><p>Welcome${u.first_name?' '+html(u.first_name):''}. Your account is ready.</p><p>Start with small entries and build a health history you can understand and bring to your next appointment.</p><p><a href="${APP}" style="display:inline-block;background:#4CAF7A;color:#0B2D24;text-decoration:none;font-weight:700;padding:11px 18px;border-radius:10px">Open Pamet</a></p>`);if(emailSent)await p.execute('UPDATE pamet_users SET confirmation_email_sent_at=NOW() WHERE id=?',[u.id])}catch{}}await audit(u.id,created?'account.created':'account.bootstrap',{emailSent});res.json({user:publicUser(u),emailSent})}catch(e){next(e)}
});
app.post('/api/feedback',auth,async(req,res,next)=>{
  try{
    const allowed=new Set(['idea','usability','bug','other']);
    const category=allowed.has(req.body.category)?req.body.category:'other';
    const message=clean(req.body.message,1000);
    const rawRating=req.body.rating;
    const rating=rawRating===null||rawRating===undefined||rawRating===''?null:Number(rawRating);
    const appVersion=clean(req.body.appVersion||'1.0.3',16);
    const screen=clean(req.body.screen||'settings',40);
    if(message.length<10)return res.status(400).json({error:'Please enter at least 10 characters of feedback.'});
    if(rating!==null&&(!Number.isInteger(rating)||rating<1||rating>5))return res.status(400).json({error:'Rating must be between 1 and 5.'});
    const p=await db();
    await p.execute('INSERT INTO pamet_feedback(id,category,rating,message,app_version,screen) VALUES(?,?,?,?,?,?)',[crypto.randomUUID(),category,rating,message,appVersion,screen]);
    res.status(201).json({saved:true});
  }catch(e){next(e)}
});
app.get('/api/billing/config',(req,res)=>res.json({publishableKey:process.env.STRIPE_PUBLISHABLE_KEY||'',proEnabled:!!(stripe&&prices.pro.monthly&&prices.pro.annual),ultraEnabled:!!(ultraEnabled&&stripe&&prices.ultra.monthly&&prices.ultra.annual),emailEnabled:!!(process.env.RESEND_API_KEY&&process.env.EMAIL_FROM)}));
app.get('/api/billing/status',auth,(req,res)=>res.json({user:publicUser(req.user)}));
async function customer(u){if(u.stripe_customer_id)return u.stripe_customer_id;const c=await stripe.customers.create({email:u.email,name:[u.first_name,u.last_name].filter(Boolean).join(' '),metadata:{pamet_user_id:String(u.id)}});const p=await db();await p.execute('UPDATE pamet_users SET stripe_customer_id=? WHERE id=?',[c.id,u.id]);return c.id}
app.post('/api/billing/create-subscription',auth,async(req,res,next)=>{
  try{if(!stripe)return res.status(503).json({error:'Stripe is not configured.'});const plan=req.body.plan==='ultra'?'ultra':'pro',interval=req.body.interval==='monthly'?'monthly':'annual';if(plan==='ultra'&&!ultraEnabled)return res.status(409).json({error:'Ultra is not available for purchase yet.'});const price=prices[plan][interval];if(!price)return res.status(503).json({error:'Stripe price is not configured.'});if(['active','trialing'].includes(req.user.subscription_status))return res.status(409).json({error:'A paid plan is already active. Use Manage your plan.'});const c=await customer(req.user),sub=await stripe.subscriptions.create({customer:c,items:[{price}],payment_behavior:'default_incomplete',payment_settings:{save_default_payment_method:'on_subscription'},trial_period_days:7,metadata:{pamet_user_id:String(req.user.id),pamet_plan:plan,pamet_interval:interval},expand:['pending_setup_intent','latest_invoice.confirmation_secret','latest_invoice.payment_intent']});const setup=sub.pending_setup_intent,confirm=sub.latest_invoice&&sub.latest_invoice.confirmation_secret,pi=sub.latest_invoice&&sub.latest_invoice.payment_intent,secret=(setup&&setup.client_secret)||(confirm&&confirm.client_secret)||(pi&&pi.client_secret);if(!secret)return res.status(500).json({error:'Stripe did not return a payment secret.'});const p=await db();await p.execute('UPDATE pamet_users SET stripe_customer_id=?,stripe_subscription_id=?,subscription_status=? WHERE id=?',[c,sub.id,sub.status,req.user.id]);res.json({clientSecret:secret,intentType:setup&&setup.client_secret?'setup':'payment',subscriptionId:sub.id,plan,interval})}catch(e){next(e)}
});
function planForPrice(id){if([prices.pro.monthly,prices.pro.annual].includes(id))return'pro';if([prices.ultra.monthly,prices.ultra.annual].includes(id))return'ultra';return'free'}
async function syncSubscription(sub){const p=await db(),uid=sub.metadata&&sub.metadata.pamet_user_id;let rows;if(uid)[rows]=await p.execute('SELECT * FROM pamet_users WHERE id=?',[uid]);else[rows]=await p.execute('SELECT * FROM pamet_users WHERE stripe_customer_id=?',[String(sub.customer)]);if(!rows.length)return;const item=sub.items?.data?.[0],price=item?.price?.id,entitled=['active','trialing'].includes(sub.status),plan=entitled?planForPrice(price):'free';await p.execute('UPDATE pamet_users SET plan=?,subscription_status=?,stripe_customer_id=?,stripe_subscription_id=? WHERE id=?',[plan,sub.status,String(sub.customer),sub.id,rows[0].id]);await audit(rows[0].id,'billing.entitlement_synced',{plan,status:sub.status})}
app.post('/api/billing/sync',auth,async(req,res,next)=>{try{if(stripe&&req.user.stripe_subscription_id){const sub=await stripe.subscriptions.retrieve(req.user.stripe_subscription_id,{expand:['pending_setup_intent','default_payment_method']});await syncSubscription(sub)}const p=await db(),[r]=await p.execute('SELECT * FROM pamet_users WHERE id=?',[req.user.id]);res.json({user:publicUser(r[0])})}catch(e){next(e)}});
app.post('/api/billing/portal',auth,async(req,res,next)=>{try{if(!stripe||!req.user.stripe_customer_id)return res.status(409).json({error:'No Stripe billing account is available.'});const s=await stripe.billingPortal.sessions.create({customer:req.user.stripe_customer_id,return_url:`${APP}/?billing=return`});res.json({url:s.url})}catch(e){next(e)}});

app.post('/api/preferences/weekly-digest',auth,async(req,res,next)=>{try{const on=!!req.body.enabled,tz=clean(req.body.timezone||'UTC',100),snap=req.body.snapshot&&typeof req.body.snapshot==='object'?JSON.stringify(req.body.snapshot):null,p=await db();await p.execute('UPDATE pamet_users SET weekly_digest_enabled=?,timezone=?,latest_digest_json=COALESCE(?,latest_digest_json) WHERE id=?',[on,tz,snap,req.user.id]);await audit(req.user.id,'digest.preference_changed',{enabled:on});res.json({enabled:on})}catch(e){next(e)}});
app.post('/api/digest/snapshot',auth,async(req,res,next)=>{try{if(!req.user.weekly_digest_enabled)return res.status(409).json({error:'Weekly digest is not enabled.'});const p=await db();await p.execute('UPDATE pamet_users SET latest_digest_json=? WHERE id=?',[JSON.stringify(req.body.snapshot||{}),req.user.id]);res.json({saved:true})}catch(e){next(e)}});
app.post('/api/jobs/weekly-digest',async(req,res,next)=>{try{const secret=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!process.env.CRON_SECRET||sha(secret)!==sha(process.env.CRON_SECRET))return res.status(401).json({error:'Unauthorized.'});const p=await db(),[users]=await p.execute('SELECT * FROM pamet_users WHERE weekly_digest_enabled=TRUE AND latest_digest_json IS NOT NULL');let sent=0;for(const u of users){const s=parse(u.latest_digest_json),top=(s.topSymptoms||[]).slice(0,3);try{if(await mail(u.email,'Your Pamet weekly summary is ready',`<h1 style="font-size:22px">Your weekly summary is ready.</h1><p>Here is your weekly Pamet overview based on the aggregate summary prepared on your device.</p><div style="background:#F4F5F2;border-radius:12px;padding:14px"><p><strong>${Number(s.loggedDays||0)}</strong> days logged</p><p><strong>${Number(s.symptomDays||0)}</strong> symptom days</p><p><strong>${Number(s.averageSleep||0).toFixed(1)}h</strong> average sleep</p></div>${top.length?`<p><strong>Most frequently recorded</strong></p><ul>${top.map(x=>`<li>${html(x.name)} — ${Number(x.count||0)} day(s)</li>`).join('')}</ul>`:''}<p>Pamet observes. Pamet does not diagnose.</p><p><a href="${APP}">Open Pamet</a></p>`))sent++}catch{}}res.json({attempted:users.length,sent})}catch(e){next(e)}});

app.get('/api/sharing/invites',auth,async(req,res,next)=>{try{const kind=['caregiver','provider'].includes(req.query.kind)?req.query.kind:null,p=await db(),[rows]=await p.execute(`SELECT id,kind,name,email,organization,status,expires_at,created_at FROM pamet_sharing_invites WHERE user_id=? ${kind?'AND kind=?':''} ORDER BY created_at DESC`,kind?[req.user.id,kind]:[req.user.id]);res.json({invites:rows.map(r=>({id:r.id,kind:r.kind,name:r.name,email:r.email,organization:r.organization,status:r.status,expiresAt:r.expires_at,createdAt:r.created_at}))})}catch(e){next(e)}});
app.post('/api/sharing/invites',auth,async(req,res,next)=>{try{if(!['pro','ultra'].includes(req.user.plan))return res.status(403).json({error:'Sharing requires Pamet Pro or Ultra.'});const kind=req.body.kind==='provider'?'provider':'caregiver',name=clean(req.body.name,100),to=clean(req.body.email,254).toLowerCase(),org=clean(req.body.organization,120),snapshot=req.body.snapshot;if(!name||!emailOk(to)||!snapshot)return res.status(400).json({error:'Name, email, and share snapshot are required.'});const p=await db();if(req.user.plan==='pro'){const [n]=await p.execute('SELECT COUNT(*) n FROM pamet_sharing_invites WHERE user_id=? AND kind=? AND status="active" AND revoked_at IS NULL AND expires_at>NOW()',[req.user.id,kind]);if(Number(n[0].n)>=1)return res.status(409).json({error:`Pro supports one active ${kind} share at a time.`})}const id=crypto.randomUUID(),raw=token(),days=kind==='provider'?14:30,expires=new Date(Date.now()+days*86400000);await p.execute('INSERT INTO pamet_sharing_invites(id,user_id,kind,name,email,organization,share_token_hash,snapshot_json,expires_at) VALUES(?,?,?,?,?,?,?,?,?)',[id,req.user.id,kind,name,to,org,sha(raw),JSON.stringify(snapshot),expires]);const url=`${APP}/share.html?token=${encodeURIComponent(raw)}`;await mail(to,'A Pamet health summary was shared with you',`<h1 style="font-size:22px">A Pamet health summary was shared with you.</h1><p>${html(req.user.first_name||'A Pamet user')} invited you to review a read-only summary.</p><p>The link expires in ${days} days and can be revoked at any time.</p><p><a href="${url}" style="display:inline-block;background:#4CAF7A;color:#0B2D24;text-decoration:none;font-weight:700;padding:11px 18px;border-radius:10px">View shared summary</a></p><p style="font-size:12px">Pamet does not provide emergency monitoring, diagnosis, or clinical alerts.</p>`);await audit(req.user.id,'sharing.invite_created',{id,kind});res.json({id,expiresInDays:days})}catch(e){next(e)}});
app.delete('/api/sharing/invites/:id',auth,async(req,res,next)=>{try{const p=await db(),[r]=await p.execute('UPDATE pamet_sharing_invites SET status="revoked",revoked_at=NOW() WHERE id=? AND user_id=?',[clean(req.params.id,36),req.user.id]);if(!r.affectedRows)return res.status(404).json({error:'Share not found.'});res.json({revoked:true})}catch(e){next(e)}});
app.get('/api/share/:token',async(req,res,next)=>{try{const raw=clean(req.params.token,256);if(raw.length<40)return res.status(404).json({error:'Share not found.'});const p=await db(),[rows]=await p.execute(`SELECT s.kind,s.name,s.organization,s.snapshot_json,s.expires_at,u.first_name owner_first_name FROM pamet_sharing_invites s JOIN pamet_users u ON u.id=s.user_id WHERE s.share_token_hash=? AND s.status='active' AND s.revoked_at IS NULL AND s.expires_at>NOW() LIMIT 1`,[sha(raw)]);if(!rows.length)return res.status(404).json({error:'This sharing link is invalid, expired, or revoked.'});const r=rows[0];res.json({kind:r.kind,recipientName:r.name,organization:r.organization,ownerFirstName:r.owner_first_name,expiresAt:r.expires_at,snapshot:parse(r.snapshot_json)})}catch(e){next(e)}});

app.use(['/db','/.github'],(req,res)=>res.status(404).end());
app.use(express.static(path.join(__dirname),{dotfiles:'ignore',extensions:['html']}));
app.use((err,req,res,next)=>{console.error(err);if(res.headersSent)return next(err);res.status(500).json({error:process.env.NODE_ENV==='production'?'Pamet could not complete that request.':err.message})});
if(require.main===module)app.listen(PORT,()=>console.log(`Pamet v1.0.3 listening on ${PORT}`));
module.exports=app;
