/* Pamet v1.5.1 service worker: bundled static shell plus user-approved Web Push; API/share data is never cached. */
const CACHE="pamet-shell-v151-0";
const SHELL=["/","/index.html","/dist/pamet.min.css?v=151","/dist/pamet.min.js?v=151","/manifest.webmanifest","/assets/pamet-mark.svg?v=151","/assets/icon-192.png","/assets/icon-512.png","/assets/icon-maskable-512.png","/assets/login-sunrise.jpg","/assets/login-dusk.jpg","/assets/login-morning.jpg"];
const PATHS=new Set(SHELL.map(path=>new URL(path,self.location.origin).pathname));
self.addEventListener("install",e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(SHELL)).then(()=>self.skipWaiting())));
self.addEventListener("activate",e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener("message",e=>{if(e.data?.type==="SKIP_WAITING")self.skipWaiting()});
self.addEventListener("push",e=>{let data={};try{data=e.data?e.data.json():{}}catch{}e.waitUntil(self.registration.showNotification(data.title||"Pamet reminder",{body:data.body||"Open Pamet to review your health journal.",icon:"/assets/icon-192.png",badge:"/assets/icon-192.png",tag:data.tag||"pamet-reminder",data:{url:data.url||"/"}}))});
self.addEventListener("notificationclick",e=>{e.notification.close();e.waitUntil(clients.matchAll({type:"window",includeUncontrolled:true}).then(windows=>{const existing=windows.find(item=>item.url.startsWith(self.location.origin));return existing?existing.focus():clients.openWindow(e.notification.data?.url||"/")}))});
self.addEventListener("fetch",e=>{const r=e.request;if(r.method!=="GET"||!r.url.startsWith(self.location.origin))return;const u=new URL(r.url);if(u.pathname.startsWith("/api/")||u.pathname.startsWith("/share"))return;const nav=r.mode==="navigate",shell=PATHS.has(u.pathname);if(!nav&&!shell)return;e.respondWith(fetch(r,{cache:"no-store"}).then(res=>{if(res?.ok&&shell){const copy=res.clone();caches.open(CACHE).then(c=>c.put(r,copy)).catch(()=>{})}return res}).catch(()=>shell?caches.match(r):nav?caches.match("/index.html"):Response.error()))});
