'use strict';
const fs = require('fs');
const check = (condition, message) => { if (!condition) throw new Error(message); };
const main = fs.readFileSync('js/main.js','utf8');
const insights = fs.readFileSync('js/insights-v1.5.0.js','utf8');
const experience = fs.readFileSync('js/experience-v1.5.0.js','utf8');
const icons = fs.readFileSync('js/icons-v1.5.0.js','utf8');
const css = fs.readFileSync('css/design-system-v1.5.0.css','utf8');
const cssMain = fs.readFileSync('css/main.css','utf8');

check(main.includes("const PAMET_VERSION = '1.5.0'"), 'Pamet browser release must be 1.5.0.');
check(main.includes('icons-v1.5.0.js') && main.includes('insights-v1.5.0.js') && main.includes('experience-v1.5.0.js'), '1.5.0 runtime layers must be bundled.');
check(cssMain.trim().endsWith('@import "./design-system-v1.5.0.css";'), 'Formal design system must load last.');
check(experience.includes("title.textContent = 'Visit Brief'") && experience.includes('Email visit brief'), 'Doctor Report must be renamed to Visit Brief in the active product UI.');
check(insights.includes("['all','All'],['symptom','Symptoms'],['lifestyle','Lifestyle'],['medication','Medications'],['sleepstress','Sleep / Stress']"), 'Insights must expose all approved observation categories.');
check(insights.includes('[7,30,90]'), 'Insights must support 7/30/90-day windows.');
check(insights.includes('First seen') && insights.includes('Last seen') && insights.includes('More frequent recently') && insights.includes('Less frequent recently'), 'Observation history and trend direction must be visible.');
check(insights.includes('Why am I seeing this?') && insights.includes('Supporting history'), 'Evidence expansion must be available.');
check(insights.includes('Data completeness') && insights.includes('Missing fields are not treated as zero'), 'Insights must explain data completeness.');
check(insights.includes('pamet_archived_observations') && insights.includes('underlying journal entries remain unchanged'), 'Archive must be view-only state and never delete health entries.');
check(insights.includes('does not establish') && insights.includes('does not infer') && !/\bcauses?\b/i.test(insights), 'Insights language must remain observational and non-causal.');
check(icons.includes('window.PametIcons') && icons.includes('stroke-width="1.8"') && icons.includes('aria-hidden="true"'), 'Central icon registry must standardize stroke and accessibility semantics.');
check(css.includes('--pamet-type-meta') && css.includes('--pamet-type-helper') && css.includes('--pamet-type-body') && css.includes('--pamet-type-control') && css.includes('--pamet-type-section') && css.includes('--pamet-type-page'), 'Formal type scale must define all approved roles.');
check(css.includes('--pamet-primary:#0f3d3e') && css.includes('--pamet-sage') && css.includes('--pamet-amber') && css.includes('--pamet-rose'), 'Semantic production colors must use teal plus health-state sage/amber/rose.');
check(!/#(?:6d28d9|7c3aed|8b5cf6|a855f7|9333ea)/i.test(css), 'Production 1.5 design layer must not introduce admin purple.');
check(experience.includes('data-calendar-today') && experience.includes('Search health history') && experience.includes('Filter by symptom'), 'Calendar must include Today, history search, and symptom filtering.');
check(experience.includes('pamet-skip-link') && experience.includes("event.key === 'Escape'") && css.includes(':focus-visible') && css.includes('prefers-reduced-motion'), 'Accessibility layer must include skip navigation, Escape handling, focus visibility, and reduced motion.');
console.log('Pamet 1.5.0 Insights/design-system checks passed.');
