'use strict';
const fs=require('fs');
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const lock=JSON.parse(fs.readFileSync('package-lock.json','utf8'));
const expected=pkg.version;
const assetVersion=expected.replace(/\D/g,'');
const versionParts=expected.split('.').map(Number);
const previousPatch=`${versionParts[0]}.${versionParts[1]}.${Math.max(0,versionParts[2]-1)}`;
const previousAssetVersion=previousPatch.replace(/\D/g,'');
const secureServer=fs.readFileSync('secure-server.js','utf8');
const server=fs.readFileSync('server.js','utf8');
const indexHtml=fs.readFileSync('index.html','utf8');
const main=fs.readFileSync('js/main.js','utf8');
const feedback=fs.readFileSync('js/feedback.js','utf8');
const worker=fs.readFileSync('sw.js','utf8');
const updateFlow=fs.readFileSync('js/version-update.js','utf8');
const legalSupport=fs.readFileSync('js/legal-support.js','utf8');
const bundle=fs.readFileSync('dist/pamet.min.js','utf8');
const mainCss=fs.readFileSync('css/main.css','utf8');
const darkMode=fs.readFileSync('css/dark-mode.css','utf8');
const readme=fs.readFileSync('README.md','utf8');
const changelog=fs.readFileSync('CHANGELOG.md','utf8');
const threatModel=fs.readFileSync('THREAT_MODEL.md','utf8');
const goLive=fs.readFileSync('GO_LIVE_STATUS.md','utf8');
const productionReadiness=fs.readFileSync('PRODUCTION_READINESS.md','utf8');
const realAcceptance=fs.readFileSync('REAL_ENVIRONMENT_ACCEPTANCE.md','utf8');
const versioning=fs.readFileSync('VERSIONING.md','utf8');
const hotfixStatus=fs.existsSync('HOTFIX_STATUS.md')?fs.readFileSync('HOTFIX_STATUS.md','utf8'):'';
const mobileContract=JSON.parse(fs.readFileSync('contracts/mobile-api.json','utf8'));
function check(condition,message){if(!condition)throw new Error(message);}
function sameRecord(a,b){
  const left=a||{};const right=b||{};
  const keys=[...new Set([...Object.keys(left),...Object.keys(right)])].sort();
  return keys.every((key)=>left[key]===right[key]);
}
check(/^\d+\.\d+\.\d+$/.test(expected),'package.json version must be semantic x.y.z.');
const declaredHotfixBaseline=hotfixStatus.includes(`# Pamet ${expected}`)&&hotfixStatus.includes(`Base release: **Pamet ${previousPatch}**`)&&hotfixStatus.includes(`Assurance baseline: **Pamet ${previousPatch}**`);
check(lock.name===pkg.name&&lock.lockfileVersion===3,'package-lock.json identity and format must remain valid.');
check(sameRecord(lock.packages?.['']?.dependencies,pkg.dependencies)&&sameRecord(lock.packages?.['']?.devDependencies,pkg.devDependencies),'package-lock.json dependency specifications must match package.json.');
check((lock.version===expected&&lock.packages?.['']?.version===expected)||(declaredHotfixBaseline&&lock.version===previousPatch&&lock.packages?.['']?.version===previousPatch),'Patch-only hotfixes may inherit the immediately previous lockfile root version only when HOTFIX_STATUS.md explicitly declares that unchanged dependency baseline.');
check(pkg.scripts.start==='node secure-server.js','Production startup must launch the secure server.');
check(!pkg.scripts.postinstall,'Do not build from postinstall.');
check(pkg.scripts.build==='node scripts/build-production.js','Production build must run the strict-CSP production bundler.');
check(secureServer.includes("require('./package.json').version"),'Production edge must source version from package.json.');
check(server.includes("const VERSION = require('./package.json').version;"),'Application server must source canonical release identity from package.json.');
check(!server.includes("const VERSION = '1.2.0';"),'Application server must not retain the historical 1.2.0 release constant.');
check(secureServer.includes("app.get('/api/health'")&&secureServer.includes('version: VERSION'),'Health must report canonical version.');
check(secureServer.includes("app.get('/sw.js'")&&secureServer.includes("Cache-Control', 'no-store, max-age=0'"),'Secure edge must serve the service worker without HTTP caching.');
check(!secureServer.includes("style-src 'self' 'unsafe-inline' https://fonts.googleapis.com"),'Emitted production style CSP must not permit unsafe-inline.');
check(!server.includes("script-src 'self' 'unsafe-inline'")&&!server.includes("style-src 'self' 'unsafe-inline'"),'Inner application CSP must not reintroduce unsafe-inline.');
check(secureServer.includes("style-src 'self' https://fonts.googleapis.com; style-src-attr 'none'"),'Production CSP must use external/self styles and block inline style attributes.');
check(server.includes("script-src-attr 'none'")&&server.includes("style-src-attr 'none'"),'Inner application CSP must block inline script/style attributes.');
const staticShellCurrent=indexHtml.includes(`dist/pamet.min.css?v=${assetVersion}`)&&indexHtml.includes(`dist/pamet.min.js?v=${assetVersion}`)&&indexHtml.includes(`assets/pamet-mark.svg?v=${assetVersion}`);
const inheritedStaticShell=declaredHotfixBaseline&&indexHtml.includes(`dist/pamet.min.css?v=${previousAssetVersion}`)&&indexHtml.includes(`dist/pamet.min.js?v=${previousAssetVersion}`)&&indexHtml.includes(`assets/pamet-mark.svg?v=${previousAssetVersion}`);
check(staticShellCurrent||inheritedStaticShell,`HTML shell must use release asset token ${assetVersion}, or the explicitly inherited ${previousAssetVersion} static-shell baseline.`);
if(inheritedStaticShell){
  check(secureServer.includes('.replace(/dist\\/pamet\\.min\\.css\\?v=\\d+/g, `dist/pamet.min.css?v=${releaseAssetVersion}`)')&&secureServer.includes('.replace(/dist\\/pamet\\.min\\.js\\?v=\\d+/g, `dist/pamet.min.js?v=${releaseAssetVersion}`)'),'Inherited static HTML must be normalized by the production edge to the active release JavaScript/CSS token.');
}
check(!/fonts\.googleapis\.com\/css2\?family=Georgia/i.test(indexHtml),'HTML shell must not request Georgia from Google Fonts.');
check(!indexHtml.includes('navigator.serviceWorker.register'),'index.html must not duplicate service-worker registration; js/main.js owns registration and updates.');
check(!indexHtml.includes('?v=1200'),'Historical hard-coded asset token v=1200 must not remain in index.html.');
check(main.includes(`const PAMET_VERSION = '${expected}'`)&&main.includes('window.PametLoadedVersion = PAMET_VERSION'),'Browser runtime must expose loaded version.');
check(main.includes(`navigator.serviceWorker.register('sw.js?v=${assetVersion}0', { updateViaCache: 'none' })`),`PWA registration must use release-specific worker token ${assetVersion}0 and bypass worker HTTP cache.`);
check(main.includes('registration.update()'),'Browser startup must explicitly request a worker update check.');
const requiredModules=['performance.js','oauth-login.js','plan-catalog.generated.js','plan-comparison.js','analytics-engine.js','tracking-intelligence.js','icons.js','account-switch.js','billing-sharing.js','feedback.js','care-planning.js','care-workspace.js','notifications.js','encrypted-sync.js','qr-sharing.js','security.js','login-experience.js','product-clarity.js','insights.js','experience.js','care-ux.js','legal-support.js','version-update.js'];
requiredModules.forEach((name)=>check(main.includes(`./${name}`),`Production entrypoint must load feature-owned module ${name}.`));
check(!/\.\/(?:[^"']*-v\d|v\d|phase2\.js)/.test(main),'Production entrypoint must not import release-numbered browser modules.');
check(!/@import\s+["'][^"']*(?:-v\d|phase2\.css)/.test(mainCss),'Production stylesheet entrypoint must not import release-numbered stylesheets.');
check(mainCss.includes('@import "./oauth-login.css";'),'Production stylesheet must include the OAuth login layer.');
check(mainCss.includes('@import "./plan-comparison.css";'),'Production stylesheet must include the plan comparison layer.');
check(mainCss.includes('@import "./tracking-intelligence.css";'),'Production stylesheet must include the tracking-intelligence layer.');
check(mainCss.includes('@import "./dark-mode.css";'),'Production stylesheet must include the unified dark-mode layer.');
check(mainCss.trim().endsWith('@import "./dark-mode.css";'),'Unified dark mode must be the final production visual override layer.');
check(darkMode.includes('--surface: #141A1E')&&darkMode.includes('--text-primary: #F2F5F4')&&darkMode.includes('.completeness-card')&&darkMode.includes('.insights-empty'),'Dark mode must retain unified dark surfaces and accessible text hierarchy.');
check(updateFlow.includes('New Pamet version available')&&updateFlow.includes('Update now')&&updateFlow.includes('does not clear your saved Pamet data'),'Safe update prompt must remain explicit.');
check(legalSupport.includes('Pamet observes. Pamet does not diagnose.')&&legalSupport.includes('not emergency monitoring')&&legalSupport.includes('HIPAA'),'Safety/privacy support wording must remain available in-app.');
check(legalSupport.includes('window.PametVersion ||'),'Safety/privacy support fallback must continue to defer to the loaded runtime version.');
check(feedback.includes('window.PametVersion ||'),'Feedback must use runtime version.');
check(worker.includes(`Pamet v${expected}`),`Service worker comment must identify Pamet ${expected}.`);
check(new RegExp(`pamet-shell-v${assetVersion}-[1-9][0-9]*`).test(worker),`Service worker cache must use a release-specific Pamet ${expected} revision.`);
check(worker.includes(`/dist/pamet.min.css?v=${assetVersion}`)&&worker.includes(`/dist/pamet.min.js?v=${assetVersion}`),'Service worker shell assets must use the current release token.');
check(!worker.includes('?v=1200'),'Historical hard-coded asset token v=1200 must not remain in the service worker.');
check(worker.includes('SKIP_WAITING')&&!worker.includes('caches.match(r,{ignoreSearch:true})'),'Service worker must activate safely without ignoring versioned asset query strings.');
check(bundle.includes('/api/health')&&bundle.includes(expected),'Generated bundle must contain current release identity.');
check(!/\bstyle\s*=\s*["']/.test(bundle),'Generated production JavaScript must not emit inline style attributes.');
const docsCurrent=readme.includes(`Version ${expected}`)&&readme.includes(`### Pamet ${expected}`)&&changelog.includes(`## [${expected}]`)&&versioning.includes(`current stable release line is \`v${expected}\``);
check(docsCurrent||declaredHotfixBaseline,'Current release documentation must identify the release, or HOTFIX_STATUS.md must explicitly declare the immediately previous patch as the unchanged assurance/documentation baseline.');
const currentState=readme.split('## Current State')[1]?.split('\n## ')[0]||'';
const staleReleaseHeading=currentState.match(/^### Pamet (\d+\.\d+\.\d+)$/m);
check(!staleReleaseHeading||staleReleaseHeading[1]===expected||declaredHotfixBaseline,`README Current State heading must match ${expected} unless the hotfix baseline is explicitly declared.`);
check(threatModel.includes(`v${expected}`)||(declaredHotfixBaseline&&threatModel.includes(`v${previousPatch}`)),'THREAT_MODEL must identify the current release or the explicitly inherited hotfix assurance baseline.');
check((goLive.includes(`Pamet ${expected}`)||declaredHotfixBaseline)&&goLive.includes('CI automation')&&goLive.includes('Independent penetration test'),'Go-live dashboard must retain CI and independent-assurance gates.');
check(productionReadiness.includes(`Pamet v${expected} Production Readiness Review`)||(declaredHotfixBaseline&&productionReadiness.includes(`Pamet v${previousPatch} Production Readiness Review`)),'PRODUCTION_READINESS must identify the current release or explicitly inherited hotfix baseline.');
check(realAcceptance.includes(`Expected repository release: **${expected}**`)||(declaredHotfixBaseline&&realAcceptance.includes(`Expected repository release: **${previousPatch}**`)),'REAL_ENVIRONMENT_ACCEPTANCE must identify the current release or explicitly inherited hotfix baseline.');
check(mobileContract.backendVersion===expected,'Mobile API contract backendVersion must match package.json version.');
check(mobileContract.minimumBackendVersion==='1.5.1','Current release must preserve the compatible native minimum backend baseline.');
check(Number(mobileContract.contractVersion)>=2,'Mobile API contract must use supported contractVersion.');
console.log(`Pamet ${expected} version, CSP, HTML/service-worker asset parity, cache-busting, module ownership, dark-mode, OAuth, plan comparison, and governance checks passed.`);
