'use strict';
const fs=require('fs');
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const expected=pkg.version;
const assetVersion=expected.replace(/\D/g,'');
const html=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('css/styles.css','utf8');
const store=fs.readFileSync('js/store.js','utf8');
const app=fs.readFileSync('js/app.js','utf8');
const main=fs.readFileSync('js/main.js','utf8');
const updateFlow=fs.readFileSync('js/version-update.js','utf8');
const planning=fs.readFileSync('js/care-planning.js','utf8');
const clarity=fs.readFileSync('js/product-clarity.js','utf8');
const insights=fs.readFileSync('js/insights.js','utf8');
const experience=fs.readFileSync('js/experience.js','utf8');
const icons=fs.readFileSync('js/icons.js','utf8');
const performance=fs.readFileSync('js/performance.js','utf8');
const design=fs.readFileSync('css/design-system.css','utf8');
const contrast=fs.readFileSync('css/contrast.css','utf8');
const mainCss=fs.readFileSync('css/main.css','utf8');
const darkMode=fs.readFileSync('css/dark-mode.css','utf8');
const reminders=fs.readFileSync('lib/appointment-reminders.js','utf8');
const workflow=fs.readFileSync('.github/workflows/push-reminders.yml','utf8');
const secureServer=fs.readFileSync('secure-server.js','utf8');
const manifest=JSON.parse(fs.readFileSync('manifest.webmanifest','utf8'));
const worker=fs.readFileSync('sw.js','utf8');
function check(condition,message){if(!condition)throw new Error(message);}
check(html.includes(`href="dist/pamet.min.css?v=${assetVersion}"`)&&html.includes(`src="dist/pamet.min.js?v=${assetVersion}"`),'Package-versioned production bundles must remain loaded.');
check(html.includes(`data-pamet-brand-release="${expected}"`)&&html.includes(`data-pamet-release="${expected}"`),'Source release markers must match package.json.');
check(!html.includes('src="js/app.js')&&!html.includes('href="css/care-planning.css'),'Source runtime layers must not load directly.');
check(/\[hidden\]\s*\{[^}]*display:\s*none\s*!important/.test(css),'Native hidden state must remain reliable.');
check(main.includes(`const PAMET_VERSION = '${expected}'`)&&main.includes('./performance.js')&&main.includes('./insights.js')&&main.includes('./experience.js')&&main.includes('./icons.js')&&main.includes('./version-update.js')&&main.includes('./oauth-login.js'),`${expected} feature-owned runtime modules must be explicit.`);
check(performance.includes('requestAnimationFrame')&&performance.includes('document.body')&&performance.includes('subtree'),'Broad mutation observers must be frame-coalesced.');
check(contrast.includes('.btn-primary')&&contrast.includes('color: #fff !important')&&contrast.includes('body.dark'),'Primary green actions must retain white text in light and dark modes.');
check(secureServer.includes('appointmentReminderJob')&&secureServer.includes("/api/jobs/appointment-reminders"),'Production edge must retain appointment reminders.');
check(reminders.includes("appointment.reminder_sent")&&reminders.includes("pamet-appointment-${appointment.id}")&&reminders.includes('GET_LOCK'),'Appointment reminders must remain deduplicated, tagged, and serialized.');
check(workflow.includes("cron: '*/15 * * * *'")&&workflow.includes('/api/jobs/appointment-reminders'),'Appointment reminder scheduler must remain active every 15 minutes.');
check(clarity.includes('Switch profile')&&clarity.includes('quickProfileButton')&&clarity.includes('S.switchProfile'),'Every screen must retain quick profile switching through the shared top bar.');
check(insights.includes('Why am I seeing this?')&&insights.includes('Data completeness')&&insights.includes('Archive')&&insights.includes('[7,30,90]'),'Insights must expose evidence, completeness, archive, and time-window controls.');
check(experience.includes("title.textContent = 'Visit Brief'")&&experience.includes('data-calendar-today')&&experience.includes('Search health history'),'Visit Brief naming and evolved Calendar controls must be active.');
check(icons.includes('window.PametIcons')&&design.includes('--pamet-type-page')&&design.includes('--pamet-primary:#0f3d3e'),'Central icon, type, and semantic color systems must ship.');
check(clarity.includes('No entry recorded for this day')&&clarity.includes('Mild symptoms')&&clarity.includes('Today'),'Calendar must distinguish missing entries from symptom-free entries and explain its legend.');
check(planning.includes('Currently viewing')&&planning.includes('Invitation sent')&&planning.includes('Discussion guide'),'Profile context, sharing confirmation, and appointment preparation must remain intact.');
check(store.includes('return [];')&&!store.includes('function sampleEntries'),'New users must start with no sample health entries.');
check(app.includes('Entry saved — Pamet is updating your patterns.'),'Saved-entry feedback must use Pamet language.');
check(manifest.display==='standalone','PWA manifest must remain standalone.');
check(main.includes(`navigator.serviceWorker.register('sw.js?v=${assetVersion}0', { updateViaCache: 'none' })`),'Service worker must register from the external production bundle with release-specific cache bypassing.');
check(worker.includes(`pamet-shell-v${assetVersion}-2`)&&worker.includes(`dist/pamet.min.js?v=${assetVersion}`)&&worker.includes(`dist/pamet.min.css?v=${assetVersion}`),'Service worker shell identity must include the current release and auth-shell revision.');
check(!worker.includes('caches.match(r,{ignoreSearch:true})'),'Versioned static assets must not ignore release query strings.');
check(worker.includes('u.pathname.startsWith("/api/")||u.pathname.startsWith("/share")'),'Sensitive API/share routes must bypass cache.');
check(mainCss.trim().endsWith('@import "./dark-mode.css";')&&darkMode.includes('.completeness-card')&&darkMode.includes('.insights-empty'),'Unified dark mode must be the final stylesheet layer and cover the Insights surfaces observed in production.');
check(updateFlow.includes('New Pamet version available')&&!updateFlow.includes('localStorage.clear'),'Safe update flow must remain visible and non-destructive.');
console.log(`Pamet v${expected} release checks passed.`);
