'use strict';
const fs=require('fs');
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const expected=pkg.version;
const secureServer=fs.readFileSync('secure-server.js','utf8');
const main=fs.readFileSync('js/main.js','utf8');
const feedback=fs.readFileSync('js/feedback-v1.0.3.js','utf8');
const worker=fs.readFileSync('sw.js','utf8');
const updateFlow=fs.readFileSync('js/version-update.js','utf8');
const legalSupport=fs.readFileSync('js/legal-support-v1.5.1.js','utf8');
const bundle=fs.readFileSync('dist/pamet.min.js','utf8');
const readme=fs.readFileSync('README.md','utf8');
const changelog=fs.readFileSync('CHANGELOG.md','utf8');
const threatModel=fs.readFileSync('THREAT_MODEL.md','utf8');
const goLive=fs.readFileSync('GO_LIVE_STATUS.md','utf8');
const mobileContract=JSON.parse(fs.readFileSync('contracts/mobile-api.json','utf8'));
function check(condition,message){if(!condition)throw new Error(message);}
check(/^\d+\.\d+\.\d+$/.test(expected),'package.json version must be semantic x.y.z.');
check(pkg.scripts.start==='node secure-server.js','Production startup must launch the secure server.');
check(!pkg.scripts.postinstall,'Do not build from postinstall.');
check(pkg.scripts.build==='node scripts/build-production.js','Production build must run the strict-CSP production bundler.');
check(secureServer.includes("require('./package.json').version"),'Production edge must source version from package.json.');
check(secureServer.includes("app.get('/api/health'")&&secureServer.includes('version: VERSION'),'Health must report canonical version.');
check(!secureServer.includes("style-src 'self' 'unsafe-inline' https://fonts.googleapis.com"),'Emitted production style CSP must not permit unsafe-inline.');
check(secureServer.includes("style-src 'self' https://fonts.googleapis.com; style-src-attr 'none'"),'Production CSP must use external/self styles and block inline style attributes.');
check(main.includes(`const PAMET_VERSION = '${expected}'`)&&main.includes('window.PametLoadedVersion = PAMET_VERSION'),'Browser runtime must expose loaded version.');
check(main.includes("navigator.serviceWorker.register('sw.js?v=1511')"),'PWA registration must execute from the CSP-compatible external production bundle.');
check(main.includes('performance-v1.5.1.js')&&main.includes('icons-v1.5.0.js')&&main.includes('insights-v1.5.0.js')&&main.includes('experience-v1.5.0.js'),'Pamet product-system and performance modules must load.');
check(main.includes('legal-support-v1.5.1.js'),'Production bundle must load in-app safety/privacy/support guidance.');
check(main.includes('version-update.js'),'Production bundle must use the stable update module.');
check(updateFlow.includes('New Pamet version available')&&updateFlow.includes('Update now')&&updateFlow.includes('does not clear your saved Pamet data'),'Safe update prompt must remain explicit.');
check(legalSupport.includes('Pamet observes. Pamet does not diagnose.')&&legalSupport.includes('not emergency monitoring')&&legalSupport.includes('HIPAA'),'Safety/privacy support wording must remain available in-app.');
check(feedback.includes('window.PametVersion ||'),'Feedback must use runtime version.');
check(worker.includes(`Pamet v${expected}`)&&worker.includes('pamet-shell-v151-1'),'Service worker cache/version must match release.');
check(worker.includes('SKIP_WAITING')&&worker.includes('ignoreSearch:true'),'Service worker must support safe activation and version-tolerant shell caching.');
check(bundle.includes('/api/health')&&bundle.includes(expected),'Generated bundle must contain current release identity.');
check(!/\bstyle\s*=\s*["']/.test(bundle),'Generated production JavaScript must not emit inline style attributes.');
check(readme.includes(`Version ${expected}`)&&readme.includes('Current State'),'README must state current release.');
check(readme.includes(`### Pamet ${expected}`),`README Current State must include a Pamet ${expected} release heading.`);
const currentState=readme.split('## Current State')[1]?.split('\n## ')[0]||'';
const staleReleaseHeading=currentState.match(/^### Pamet (\d+\.\d+\.\d+)$/m);
check(!staleReleaseHeading||staleReleaseHeading[1]===expected,`README Current State heading must match ${expected}.`);
check(changelog.includes(`## [${expected}]`),'CHANGELOG must contain current release.');
check(threatModel.includes(`v${expected}`)&&!threatModel.includes('Pamet v1.2.0'),'THREAT_MODEL must identify the current release baseline.');
check(goLive.includes(`Pamet ${expected}`)&&goLive.includes('CI automation')&&goLive.includes('Independent penetration test'),'Go-live dashboard must track current release and independent gates.');
check(mobileContract.backendVersion===expected,'Mobile API contract backendVersion must match package.json version.');
check(Number(mobileContract.contractVersion)>=2,'Mobile API contract must use supported contractVersion.');
console.log(`Pamet ${expected} version, CSP, and governance checks passed.`);
