'use strict';
const fs = require('fs');
const check = (condition, message) => { if (!condition) throw new Error(message); };
const main = fs.readFileSync('js/main.js','utf8');
const insights = fs.readFileSync('js/insights.js','utf8');
const experience = fs.readFileSync('js/experience.js','utf8');
const icons = fs.readFileSync('js/icons.js','utf8');
const css = fs.readFileSync('css/design-system.css','utf8');
const cssMain = fs.readFileSync('css/main.css','utf8');

check(main.includes("const PAMET_VERSION = '1.6.0'"), 'Pamet browser release must identify the 1.6.0 product-system line.');
check(main.includes('./icons.js') && main.includes('./insights.js') && main.includes('./experience.js'), 'Feature-owned product-system runtime layers must remain bundled.');
check(cssMain.includes('@import "./design-system.css";'), 'Formal design system must remain loaded.');
check(experience.includes("title.textContent = 'Visit Brief'") && experience.includes('Email visit brief'), 'Doctor Report must remain renamed to Visit Brief in the active product UI.');
check(insights.includes("['all','All'],['symptom','Symptoms'],['lifestyle','Lifestyle'],['medication','Medications'],['sleepstress','Sleep / Stress']"), 'Insights must expose all approved observation categories.');
check(insights.includes('[7,30,90]'), 'Insights must support 7/30/90-day windows.');
check(insights.includes('First seen') && insights.includes('Last seen') && insights.includes('More frequent recently') && insights.includes('Less frequent recently'), 'Observation history and trend direction must be visible.');
check(insights.includes('Why am I seeing this?') && insights.includes('Supporting history'), 'Evidence expansion must be available.');
check(insights.includes('Data completeness') && insights.includes('Missing fields are not treated as zero'), 'Insights must explain data completeness.');
check(insights.includes('pamet_archived_observations') && insights.includes('underlying journal entries remain unchanged'), 'Archive must be view-only state and never delete health entries.');
check(insights.includes('does not establish') && insights.includes('does not infer') && !/(?:\bcauses\b|\bcaused by\b|\bleads to\b|→)/i.test(insights), 'Insights language must remain observational and non-causal.');
check(icons.includes('window.PametIcons') && icons.includes('stroke-width="1.8"') && icons.includes('aria-hidden="true"'), 'Central icon registry must standardize stroke and accessibility semantics.');
check(css.includes('--pamet-type-meta') && css.includes('--pamet-type-helper') && css.includes('--pamet-type-body') && css.includes('--pamet-type-control') && css.includes('--pamet-type-section') && css.includes('--pamet-type-page'), 'Formal type scale must define all approved roles.');
check(css.includes('--pamet-primary:#0f3d3e') && css.includes('--pamet-sage') && css.includes('--pamet-amber') && css.includes('--pamet-rose'), 'Semantic production colors must use teal plus health-state sage/amber/rose.');
check(!/#(?:6d28d9|7c3aed|8b5cf6|a855f7|9333ea)/i.test(css), 'Production design layer must not introduce admin purple.');
check(experience.includes('data-calendar-today') && experience.includes('Search health history') && experience.includes('Filter by symptom'), 'Calendar must include Today, history search, and symptom filtering.');
check(experience.includes('pamet-skip-link') && experience.includes("event.key === 'Escape'") && css.includes(':focus-visible') && css.includes('prefers-reduced-motion'), 'Accessibility layer must include skip navigation, Escape handling, focus visibility, and reduced motion.');
console.log('Pamet 1.6.0 Insights/design-system checks passed.');
