'use strict';
const fs=require('fs');
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const expected='1.5.1';
const secureServer=fs.readFileSync('secure-server.js','utf8');
const main=fs.readFileSync('js/main.js','utf8');
const feedback=fs.readFileSync('js/feedback-v1.0.3.js','utf8');
const worker=fs.readFileSync('sw.js','utf8');
const updateFlow=fs.readFileSync('js/version-update.js','utf8');
const bundle=fs.readFileSync('dist/pamet.min.js','utf8');
const readme=fs.readFileSync('README.md','utf8');
const changelog=fs.readFileSync('CHANGELOG.md','utf8');
function check(condition,message){if(!condition)throw new Error(message);}
check(pkg.version===expected,`package.json must identify Pamet ${expected}.`);
check(pkg.scripts.start==='node secure-server.js','Production startup must launch the secure server.');
check(!pkg.scripts.postinstall,'Do not build from postinstall.');
check(pkg.scripts.build?.includes('esbuild js/main.js'),'Production build command must bundle current source.');
check(secureServer.includes("require('./package.json').version"),'Production edge must source version from package.json.');
check(secureServer.includes("app.get('/api/health'")&&secureServer.includes('version: VERSION'),'Health must report canonical version.');
check(main.includes(`const PAMET_VERSION = '${expected}'`)&&main.includes('window.PametLoadedVersion = PAMET_VERSION'),'Browser runtime must expose loaded version.');
check(main.includes("navigator.serviceWorker.register('sw.js?v=1511')"),'PWA registration must execute from the CSP-compatible external production bundle.');
check(main.includes('performance-v1.5.1.js')&&main.includes('icons-v1.5.0.js')&&main.includes('insights-v1.5.0.js')&&main.includes('experience-v1.5.0.js'),'Pamet product-system and performance modules must load.');
check(main.includes('version-update.js'),'Production bundle must use the stable update module.');
check(updateFlow.includes('New Pamet version available')&&updateFlow.includes('Update now')&&updateFlow.includes('does not clear your saved Pamet data'),'Safe update prompt must remain explicit.');
check(feedback.includes('window.PametVersion ||'),'Feedback must use runtime version.');
check(worker.includes(`Pamet v${expected}`)&&worker.includes('pamet-shell-v151-1'),'Service worker cache/version must match release.');
check(worker.includes('SKIP_WAITING')&&worker.includes('ignoreSearch:true'),'Service worker must support safe activation and version-tolerant shell caching.');
check(bundle.includes('/api/health')&&bundle.includes(expected),'Generated bundle must contain current release identity.');
check(readme.includes(`Version ${expected}`)&&readme.includes('Current State'),'README must state current release.');
check(changelog.includes(`## [${expected}]`),'CHANGELOG must contain current release.');
console.log(`Pamet ${expected} version checks passed.`);
