'use strict';
const fs=require('fs');
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const expected=pkg.version;
const assetVersion=expected.replace(/\D/g,'');
const html=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('css/styles.css','utf8');
const store=fs.readFileSync('js/store.js','utf8');
const app=fs.readFileSync('js/app.js','utf8');
const main=fs.readFileSync('js/main.js','utf8');
const authenticated=fs.readFileSync('js/authenticated-features.js','utf8');
const updateFlow=fs.readFileSync('js/version-update.js','utf8');
const planning=fs.readFileSync('js/care-planning.js','utf8');
const clarity=fs.readFileSync('js/product-clarity.js','utf8');
const insights=fs.readFileSync('js/insights.js','utf8');
const experience=fs.readFileSync('js/experience.js','utf8');
const icons=fs.readFileSync('js/icons.js','utf8');
const performance=fs.readFileSync('js/performance.js','utf8');
const planComparison=fs.readFileSync('js/plan-comparison.js','utf8');
const planComparisonCss=fs.readFileSync('css/plan-comparison.css','utf8');
const design=fs.readFileSync('css/design-system.css','utf8');
const contrast=fs.readFileSync('css/contrast.css','utf8');
const mainCss=fs.readFileSync('css/main.css','utf8');
const authenticatedCss=fs.readFileSync('css/authenticated.css','utf8');
const darkMode=fs.readFileSync('css/dark-mode.css','utf8');
const reminders=fs.readFileSync('lib/appointment-reminders.js','utf8');
const workflow=fs.readFileSync('.github/workflows/push-reminders.yml','utf8');
const secureServer=fs.readFileSync('secure-server.js','utf8');
const manifest=JSON.parse(fs.readFileSync('manifest.webmanifest','utf8'));
const assetManifest=JSON.parse(fs.readFileSync('dist/asset-manifest.json','utf8'));
const worker=fs.readFileSync('sw.js','utf8');
function check(condition,message){if(!condition)throw new Error(message);}
check(html.includes(`href="dist/pamet.min.css?v=${assetVersion}"`)&&html.includes(`src="dist/pamet.min.js?v=${assetVersion}"`),'Source production HTML must retain stable compatibility bundle references for the edge renderer.');
check(html.includes(`href="assets/pamet-mark.svg?v=${assetVersion}"`),'Production HTML must load the current release-tokened brand mark.');
check(!html.includes('?v=1200')&&!html.includes('navigator.serviceWorker.register'),'Historical shell token and duplicate inline worker registration must not return.');
check(!/fonts\.googleapis\.com\/css2\?family=Georgia/i.test(html),'Production HTML must not request Georgia from Google Fonts.');
check(!html.includes('src="js/app.js')&&!html.includes('href="css/care-planning.css'),'Source runtime layers must not load directly.');
check(/\[hidden\]\s*\{[^}]*display:\s*none\s*!important/.test(css),'Native hidden state must remain reliable.');
const eager=['performance.js','icons.js','version-update.js','oauth-login.js','plan-catalog.generated.js','entitlement-guard.js','security.js'];
const deferred=['insights.js','experience.js','plan-comparison.js','care-planning.js','care-workspace.js','billing-sharing.js'];
eager.forEach((name)=>check(main.includes(`./${name}`),`${expected} eager runtime module ${name} must remain explicit.`));
deferred.forEach((name)=>check(authenticated.includes(`./${name}`)&&!main.includes(`import "./${name}"`),`${expected} deferred runtime module ${name} must remain explicit and out of signed-out startup.`));
check(main.includes('loadAuthenticatedFeatures')&&main.includes('navigator.connection?.saveData'),'Authenticated feature code must be session-lazy and network-aware.');
check(performance.includes('requestAnimationFrame')&&performance.includes('document.body')&&performance.includes('subtree'),'Remaining broad mutation observers must be frame-coalesced by the performance guard.');
check(!/new\s+MutationObserver[\s\S]{0,500}\.observe\(document\.(?:body|documentElement)\s*,\s*\{[^}]*childList\s*:\s*true[^}]*subtree\s*:\s*true[^}]*\}\s*\)/m.test(experience),'Experience refresh must use explicit lifecycle/navigation events instead of observing the whole page.');
check(contrast.includes('.btn-primary')&&contrast.includes('color: #fff !important')&&contrast.includes('body.dark'),'Primary green actions must retain white text in light and dark modes.');
check(secureServer.includes('appointmentReminderJob')&&secureServer.includes("/api/jobs/appointment-reminders"),'Production edge must retain appointment reminders.');
check(reminders.includes("appointment.reminder_sent")&&reminders.includes("pamet-appointment-${appointment.id}")&&reminders.includes('GET_LOCK'),'Appointment reminders must remain deduplicated, tagged, and serialized.');
check(workflow.includes("cron: '*/15 * * * *'")&&workflow.includes('/api/jobs/appointment-reminders'),'Appointment reminder scheduler must remain active every 15 minutes.');
check(clarity.includes('Switch profile')&&clarity.includes('quickProfileButton')&&clarity.includes('S.switchProfile'),'Every screen must retain quick profile switching through the shared top bar.');
check(insights.includes('Why am I seeing this?')&&insights.includes('Data completeness')&&insights.includes('Archive')&&insights.includes('[7,30,90]'),'Insights must expose evidence, completeness, archive, and time-window controls.');
check(experience.includes("title.textContent = 'Visit Brief'")&&experience.includes('data-calendar-today')&&experience.includes('Search health history'),'Visit Brief naming and evolved Calendar controls must be active.');
check(icons.includes('window.PametIcons')&&design.includes('--pamet-type-page')&&design.includes('--pamet-primary:#0f3d3e'),'Central icon, type, and semantic color systems must ship.');
check(clarity.includes('No entry recorded for this day')&&clarity.includes('Mild symptoms')&&clarity.includes('Today'),'Calendar must distinguish missing entries from symptom-free entries and explain its legend.');
check(planning.includes('Currently viewing')&&planning.includes('Invitation sent')&&planning.includes('Discussion guide'),'Profile context, sharing confirmation, and appointment preparation must remain intact.');
check(planComparison.includes('Compare all plans')&&planComparison.includes('Upgrade to Pro')&&planComparison.includes('Upgrade to Ultra')&&planComparison.includes('Compare all plan features')&&planComparison.includes('PametPlanCatalog'),'Canonical plan comparison and next-tier upgrade actions must remain active.');
check(planComparisonCss.includes('grid-column:1 / -1')&&planComparisonCss.includes('.plan-upgrade-modal')&&planComparisonCss.includes('width:min(760px'),'Plan actions and paid-tier chooser must retain the aligned responsive layout.');
check(store.includes('return [];')&&!store.includes('function sampleEntries'),'New users must start with no sample health entries.');
check(app.includes('Entry saved — Pamet is updating your patterns.'),'Saved-entry feedback must use Pamet language.');
check(manifest.display==='standalone','PWA manifest must remain standalone.');
check(new RegExp(`navigator\\.serviceWorker\\.register\\('sw\\.js\\?v=${assetVersion}[1-9][0-9]*'`).test(main),'Service worker must register from the external production bundle with a release-specific cache revision.');
check(new RegExp(`pamet-shell-v${assetVersion}-[1-9][0-9]*`).test(worker)&&worker.includes('/dist/asset-manifest.json'),'Service worker shell identity must include the current release and discover content-hashed assets from the manifest.');
check(!worker.includes('caches.match(r,{ignoreSearch:true})'),'Versioned static assets must not use the historical ignore-search lookup; the offline HTML fallback may ignore a navigation query string.');
check(worker.includes("url.pathname.startsWith('/api/')||url.pathname.startsWith('/share')"),'Sensitive API/share routes must bypass cache.');
for(const key of ['bootstrapJs','featuresJs','bootstrapCss','featuresCss'])check(/^\/dist\/pamet\.(?:bootstrap|features|styles)\.[a-f0-9]{12}\.(?:js|css)$/.test(assetManifest[key]||''),`Release asset manifest ${key} must be content hashed.`);
check(mainCss.trim().endsWith('@import "./dark-mode.css";')&&authenticatedCss.trim().endsWith('@import "./dark-mode.css";')&&darkMode.includes('.completeness-card')&&darkMode.includes('.insights-empty'),'Unified dark mode must be final in both full and deferred stylesheet layers and cover Insights.');
check(updateFlow.includes('New Pamet version available')&&!updateFlow.includes('localStorage.clear'),'Safe update flow must remain visible and non-destructive.');
console.log(`Pamet v${expected} release checks passed with split bundles, immutable release assets, and preserved product contracts.`);
